/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pokedex.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Pokemon service. Represents a row in the &quot;Pokemon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.pokedex.model.impl.PokemonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.pokedex.model.impl.PokemonImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pokemon
 * @see com.liferay.pokedex.model.impl.PokemonImpl
 * @see com.liferay.pokedex.model.impl.PokemonModelImpl
 * @generated
 */
@ProviderType
public interface PokemonModel extends BaseModel<Pokemon>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pokemon model instance should use the {@link Pokemon} interface instead.
	 */

	/**
	 * Returns the primary key of this pokemon.
	 *
	 * @return the primary key of this pokemon
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pokemon.
	 *
	 * @param primaryKey the primary key of this pokemon
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pokemon.
	 *
	 * @return the uuid of this pokemon
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this pokemon.
	 *
	 * @param uuid the uuid of this pokemon
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this pokemon.
	 *
	 * @return the ID of this pokemon
	 */
	public long getId();

	/**
	 * Sets the ID of this pokemon.
	 *
	 * @param id the ID of this pokemon
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this pokemon.
	 *
	 * @return the group ID of this pokemon
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pokemon.
	 *
	 * @param groupId the group ID of this pokemon
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pokemon.
	 *
	 * @return the company ID of this pokemon
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pokemon.
	 *
	 * @param companyId the company ID of this pokemon
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pokemon.
	 *
	 * @return the user ID of this pokemon
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pokemon.
	 *
	 * @param userId the user ID of this pokemon
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pokemon.
	 *
	 * @return the user uuid of this pokemon
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pokemon.
	 *
	 * @param userUuid the user uuid of this pokemon
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pokemon.
	 *
	 * @return the user name of this pokemon
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pokemon.
	 *
	 * @param userName the user name of this pokemon
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pokemon.
	 *
	 * @return the create date of this pokemon
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pokemon.
	 *
	 * @param createDate the create date of this pokemon
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pokemon.
	 *
	 * @return the modified date of this pokemon
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pokemon.
	 *
	 * @param modifiedDate the modified date of this pokemon
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the original name of this pokemon.
	 *
	 * @return the original name of this pokemon
	 */
	@AutoEscape
	public String getOriginalName();

	/**
	 * Sets the original name of this pokemon.
	 *
	 * @param originalName the original name of this pokemon
	 */
	public void setOriginalName(String originalName);

	/**
	 * Returns the custom name of this pokemon.
	 *
	 * @return the custom name of this pokemon
	 */
	@AutoEscape
	public String getCustomName();

	/**
	 * Sets the custom name of this pokemon.
	 *
	 * @param customName the custom name of this pokemon
	 */
	public void setCustomName(String customName);

	/**
	 * Returns the description of this pokemon.
	 *
	 * @return the description of this pokemon
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this pokemon.
	 *
	 * @param description the description of this pokemon
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this pokemon.
	 *
	 * @return the type of this pokemon
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this pokemon.
	 *
	 * @param type the type of this pokemon
	 */
	public void setType(String type);

	/**
	 * Returns the order of this pokemon.
	 *
	 * @return the order of this pokemon
	 */
	public long getOrder();

	/**
	 * Sets the order of this pokemon.
	 *
	 * @param order the order of this pokemon
	 */
	public void setOrder(long order);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Pokemon pokemon);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Pokemon> toCacheModel();

	@Override
	public Pokemon toEscapedModel();

	@Override
	public Pokemon toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}